name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'

      - name: Set project
        run: gcloud config set project ${{ secrets.GCLOUD_PROJECT }}

      - name: Build & Push Container
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/securitytrails-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy securitytrails-app \
            --image gcr.io/${{ secrets.GCLOUD_PROJECT }}/securitytrails-app \
            --platform managed \
            --region ${{ secrets.GCLOUD_REGION }} \
            --allow-unauthenticated \
            --set-env-vars SECURITYTRAILS_API_KEY=${{ secrets.SECURITYTRAILS_API_KEY }} \
            --set-env-vars PORT=4000